version: 0.0.{build}
image:
  - Visual Studio 2019
configuration: Release
environment:
  matrix:
    - platform: x64
install:
  - vcpkg install librdkafka[*]:x64-windows --recurse
  - vcpkg install spdlog:x64-windows
cache: c:\tools\vcpkg\installed
before_build:
  - ps: win\build.ps1
artifacts:
  - path: kafkaui_win64.zip
    name: App
deploy:
  - provider: S3
    access_key_id:
      secure: YZGJ4/DWRlBCwNSu/UH5DLDjlEER4g6x6OHbqMXYCSA=
    secret_access_key:
      secure: FU/U7Gbtz/362xNQEVS+2keJ+iDUzwYwU9Hf9T5tdRN0g0ig9ovaiqTGm/peeBIa
    region: eu-central-1
    bucket: kafkaui-ci-packages
    folder: kafkaui/(APPVEYOR_REPO_TAG_NAME)
    artifact: App
    max_error_retry: 3
    on:
      APPVEYOR_REPO_TAG: true
notifications:
  - provider: Email
    to:
      - dmitriy.mukhitov@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true