version: 0.0.{build}
image:
  - Visual Studio 2019
configuration: Release
environment:
  matrix:
    - platform: x64
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install librdkafka[*]:x64-windows --recurse
  - vcpkg install spdlog:x64-windows
  - vcpkg install boost-core:x64-windows
  - vcpkg install boost-format:x64-windows
  - vcpkg install boost-circular-buffer:x64-windows
  - vcpkg install boost-any:x64-windows
  - vcpkg install boost-filesystem:x64-windows
  - vcpkg install boost-iostreams:x64-windows
  - vcpkg install boost-algorithm:x64-windows
  - vcpkg install boost-math:x64-windows
  - vcpkg install boost-crc:x64-windows
  - vcpkg install protobuf:x64-windows
  - vcpkg install snappy:x64-windows
#cache: c:\tools\vcpkg\installed
before_build:
  - ps: win\build.ps1
artifacts:
  - path: plumber_win64.zip
    name: App
#deploy:
#  - provider: S3
#    access_key_id:
#      secure: YZGJ4/DWRlBCwNSu/UH5DLDjlEER4g6x6OHbqMXYCSA=
#    secret_access_key:
#      secure: FU/U7Gbtz/362xNQEVS+2keJ+iDUzwYwU9Hf9T5tdRN0g0ig9ovaiqTGm/peeBIa
#    region: eu-central-1
#    bucket: kafkaui-ci-packages
#    folder: kafkaui/$(APPVEYOR_REPO_TAG_NAME)
#    artifact: App
#    max_error_retry: 3
#    on:
#      APPVEYOR_REPO_TAG: true
notifications:
  - provider: Email
    to:
      - dmitriy.mukhitov@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true